# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
podfile: Example/Podfile
env:
  matrix:
    - NAME='iPhone 6s'
    - NAME='iPhone 6s Plus'
script:
- set -o pipefail && xcodebuild test -workspace Example/Dezignables.xcworkspace -scheme Dezignables-Example -destination "platform=iOS Simulator,name=$NAME" ONLY_ACTIVE_ARCH=NO | xcpretty
